# Generated by Django 4.1.8 on 2023-04-09 06:45

from django.db import migrations
import typeclasses.objects


class Migration(migrations.Migration):
    dependencies = [
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultObject",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.objectdb",),
        ),
        migrations.CreateModel(
            name="DefaultCharacter",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.defaultobject",),
        ),
        migrations.CreateModel(
            name="DefaultExit",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.defaultobject",),
        ),
        migrations.CreateModel(
            name="DefaultRoom",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.defaultobject",),
        ),
        migrations.CreateModel(
            name="Object",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(typeclasses.objects.ObjectParent, "objects.defaultobject"),
        ),
        migrations.CreateModel(
            name="Character",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(typeclasses.objects.ObjectParent, "objects.defaultcharacter"),
        ),
    ]
