# Generated by Django 4.1.8 on 2023-04-09 06:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comms", "0022_defaultchannel_alter_channeldb_id_alter_msg_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultChannel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("comms.channeldb",),
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("comms.defaultchannel",),
        ),
    ]
